projectDir = "/home/jappie/projects"
template = "haskell-template-project"

# which branch to checkout from master
workbranch = "jyggalag-update"

# [projects.mysql_haskell]
# path = "mysql-haskell"

# [projects.poppen]
# path = "poppen"

[projects.plunder]
path = "plunder"
ignoreActions = ["nightly.yaml"]

# [projects.persistent_mysql_haskell]
# path = "persistent"

# [projects.llvm_party]
# path = "llvm-party"

# [projects.jappie_lang]
# path = "jappie-lang"